[package]
name = "declio"
version = "0.1.0"
authors = ["Adam Gausmann <agausmann@fastmail.com>"]
edition = "2018"

[features]
default = ["derive"]
derive = ["declio_derive"]

[dependencies]
declio_derive = { path = "../declio_derive", version = "0.1", optional = true }
